### ISSUE TITLE
Release v1.7.0

### ISSUE THREAD

**Issue by parkr** [hubot-scripts/hubot-github-repo-event-notifier#35]
Hey @patcon! It would be wonderful if you could release a v1.7.0. It contains #34 and would be a wonderful addition to the library. Alternatively, you could give me publishing abilities on NPM. Thanks!

**Comment by patcon** [comment]
Oy missed this, but I can give you npm pub rights! twitter DM me the right email? @patconnolly

**Comment by patcon** [comment]
nevermind, gave you pub access! sorry for terrible delay parker!

**Comment by parkr** [comment]
Published, thank you! https://www.npmjs.com/package/hubot-github-repo-event-notifier
