### ISSUE TITLE
New co-maintainer

### ISSUE THREAD

**Issue by patcon** [hubot-scripts/hubot-github-repo-event-notifier#43]
Hey @parkr, @strugee was asking about getting co-maintainer status on this repo:
https://twitter.com/strugee2/status/940069654667472896

I'm not actively using it anymore, so I wanted to check with you that it's ok. (It's just you and I with push access + org owners)

I'll give @parkr a week to reply, and then add you @strugee -- just wanted to make sure I'm not treading on @parkr's toes :)

**Comment by strugee** [comment]
LGTM! Thanks <3

**Comment by parkr** [comment]
@patcon Thanks for asking! Big 👍 from me.

**Comment by strugee** [comment]
Yikes, only just saw your invite @patcon - thanks so much y'all!

**Comment by strugee** [comment]
@patcon @parkr can one of you run `npm owner add strugee hubot-github-repo-event-notifier`? I want to push out a new release soon; I added a number of improvements in #47 :thumbsup:

**Comment by parkr** [comment]
@strugee Done, I think!

**Comment by strugee** [comment]
LGTM, thank you! :tada:

**Comment by patcon** [comment]
Thanks @strugee! (and @parkr, for being quicker than I ;) )

**Comment by strugee** [comment]
Sure thing! I'm going to clean up the test suite and then release the changes I made in #47.
