### ISSUE TITLE
Allow `event_type:action` format for enabling notifications

### ISSUE THREAD

**Issue by patcon** [hubot-scripts/hubot-github-repo-event-notifier#9]
Right now, we're checking for `"action": "opened"` in the payload, and then checking for a key with the enabled event types (from `HUBOT_GITHUB_EVENT_NOTIFIER_TYPES`).

Just realized that we could instead expect the format for the envvar to be:

    HUBOT_GITHUB_EVENT_NOTIFIER_TYPES="issue:opened,pull_request:opened"

Perhaps we could default to the `opened` action if not specified (and down the line, perhaps have a hash specifying the default for each type).

**Comment by geekgonecrazy** [comment]
Looks like this could probably be closed now?

**Comment by patcon** [comment]
:+1:
